### ISSUE TITLE
Apply Spring IO Platform 1.1

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/terasoluna-gfw#205]
Related issue : #132 

- [x] Apply 1.1.0.BUILD-SNAPSHOT (#221)
- [x] Apply 1.1.0.RELEASE  (#225)
- [x] Remove snapshot repository of spring (#225)
- [x] Apply hibernate-validator's bug (see [HV-949](https://hibernate.atlassian.net/browse/HV-949) or https://github.com/terasolunaorg/terasoluna-gfw/issues/205#issuecomment-64752586 .) -> Added the description to apply the temporary workaround in the guideline.
- [x] Apply 1.1.1.RELEASE

**[1.1.0.RELEASE(2014/12/18)]** 
difference with 1.0.3.RELEASE

[compile or runtime]
* `org.springframework:spring-xxx` : 4.0.8.RELEASE -> 4.1.3.BUILD-SNAPSHOT -> 4.1.3.RELEASE
* `org.apache.tiles:tiles-request-api` : 1.0.1 -> 1.0.6
* `com.fasterxml.jackson.xxx:jackson-xxx` : 2.3.4 -> 2.4.4
* `org.hibernate:hibernate-validator` : 5.0.3.Final -> 5.1.3.Final
* `org.springframework.data:spring-data-commons` : 1.8.4.RELEASE -> 1.9.1.RELEASE
* `org.springframework.data:spring-data-jpa` : 1.6.4.RELEASE -> 1.7.1.RELEASE
* `joda-time:joda-time` : 2.3 -> 2.5
* `org.apache.commons:commons-lang3` : 3.1 -> 3.3.2

[test or provided]
* `com.h2database:h2` : 1.3.176 -> 1.4.182
* `org.mockito:mockito-core` : 1.9.5 -> 1.10.8
* `junit:junit` : 4.11 -> 4.12 -> 4.11
* `org.apache.tomcat:*` : 7.0.56 -> 7.0.57

**[1.1.1.RELEASE(2015/1/16)]** 
difference with 1.1.0.RELEASE

[parent]
* org.springframework.boot:xxx : 1.2.0.RELEASE -> 1.2.1.RELEASE

[compile or runtime]
* `org.springframework:spring-xxx` : 4.1.3.RELEASE -> 4.1.4.RELEASE
* org.slf4j:xxx : 1.7.7 -> 1.7.8

[test or provided]
* `com.h2database:h2` : 1.4.182 -> 1.4.183

**Comment by btshimizukza** [comment]
Apply 1.1.1.RELEASE.
